version: '3'

services:
    database:
      build: ./database
      restart: always
      environment:
        POSTGRES_HOST_AUTH_METHOD: trust
      ports:
        - 5432:5432
      #volumes:
      #- db-volume:/var/lib/postgres
    backend:
      build: ./backend
      restart: always
      ports:
        - 5000:5000

volumes:
  db-volume:
